<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Gateway\Paypal\ProcessController as PaypalController;
use App\Http\Controllers\Gateway\PaypalSdk\ProcessController as PaypalSdkController;
use App\Http\Controllers\Gateway\PerfectMoney\ProcessController as PerfectMoneyController;
use App\Http\Controllers\Gateway\Stripe\ProcessController as StripeController;
use App\Http\Controllers\Gateway\StripeJs\ProcessController as StripeJsController;
use App\Http\Controllers\Gateway\StripeV3\ProcessController as StripeV3Controller;
use App\Http\Controllers\Gateway\Skrill\ProcessController as SkrillController;
use App\Http\Controllers\Gateway\Paytm\ProcessController as PaytmController;
use App\Http\Controllers\Gateway\Payeer\ProcessController as PayeerController;
use App\Http\Controllers\Gateway\Paystack\ProcessController as PaystackController;
use App\Http\Controllers\Gateway\Flutterwave\ProcessController as FlutterwaveController;
use App\Http\Controllers\Gateway\Razorpay\ProcessController as RazorpayController;
use App\Http\Controllers\Gateway\Instamojo\ProcessController as InstamojoController;
use App\Http\Controllers\Gateway\Blockchain\ProcessController as BlockchainController;
use App\Http\Controllers\Gateway\Coinpayments\ProcessController as CoinpaymentsController;
use App\Http\Controllers\Gateway\CoinpaymentsFiat\ProcessController as CoinpaymentsFiatController;
use App\Http\Controllers\Gateway\Coingate\ProcessController as CoingateController;
use App\Http\Controllers\Gateway\CoinbaseCommerce\ProcessController as CoinbaseCommerceController;
use App\Http\Controllers\Gateway\Mollie\ProcessController as MollieController;
use App\Http\Controllers\Gateway\Cashmaal\ProcessController as CashmaalController;
use App\Http\Controllers\Gateway\MercadoPago\ProcessController as MercadoPagoController;
use App\Http\Controllers\Gateway\Authorize\ProcessController as AuthorizeController;
use App\Http\Controllers\Gateway\NMI\ProcessController as NMIController;
use App\Http\Controllers\Gateway\BTCPay\ProcessController as BTCPayController;
use App\Http\Controllers\Gateway\NowPaymentsHosted\ProcessController as NowPaymentsHostedController;
use App\Http\Controllers\Gateway\NowPaymentsCheckout\ProcessController as NowPaymentsCheckoutController;
use App\Http\Controllers\Gateway\TwoCheckout\ProcessController as TwoCheckoutController;
use App\Http\Controllers\Gateway\Checkout\ProcessController as CheckoutController;
use App\Http\Controllers\Gateway\SslCommerz\ProcessController as SslCommerzController;
use App\Http\Controllers\Gateway\Aamarpay\ProcessController as AamarpayController;
use App\Http\Controllers\Gateway\Binance\ProcessController as BinanceController;
use App\Http\Controllers\Gateway\PaymentController;

Route::post('paypal', [PaypalController::class, 'ipn'])->name('Paypal');
Route::get('paypal-sdk', [PaypalSdkController::class, 'ipn'])->name('PaypalSdk');
Route::post('perfect-money', [PerfectMoneyController::class, 'ipn'])->name('PerfectMoney');
Route::post('stripe', [StripeController::class, 'ipn'])->name('Stripe');
Route::post('stripe-js', [StripeJsController::class, 'ipn'])->name('StripeJs');
Route::post('stripe-v3', [StripeV3Controller::class, 'ipn'])->name('StripeV3');
Route::post('skrill', [SkrillController::class, 'ipn'])->name('Skrill');
Route::post('paytm', [PaytmController::class, 'ipn'])->name('Paytm');
Route::post('payeer', [PayeerController::class, 'ipn'])->name('Payeer');
Route::post('paystack', [PaystackController::class, 'ipn'])->name('Paystack');
Route::get('flutterwave/{trx}/{type}', [FlutterwaveController::class, 'ipn'])->name('Flutterwave');
Route::post('razorpay', [RazorpayController::class, 'ipn'])->name('Razorpay');
Route::post('instamojo', [InstamojoController::class, 'ipn'])->name('Instamojo');
Route::get('blockchain', [BlockchainController::class, 'ipn'])->name('Blockchain');
Route::post('coinpayments', [CoinpaymentsController::class, 'ipn'])->name('Coinpayments');
Route::post('coinpayments-fiat', [CoinpaymentsFiatController::class, 'ipn'])->name('CoinpaymentsFiat');
Route::post('coingate', [CoingateController::class, 'ipn'])->name('Coingate');
Route::post('coinbase-commerce', [CoinbaseCommerceController::class, 'ipn'])->name('CoinbaseCommerce');
Route::get('mollie', [MollieController::class, 'ipn'])->name('Mollie');
Route::post('cashmaal', [CashmaalController::class, 'ipn'])->name('Cashmaal');
Route::post('mercado-pago', [MercadoPagoController::class, 'ipn'])->name('MercadoPago');
Route::post('authorize', [AuthorizeController::class, 'ipn'])->name('Authorize');
Route::get('nmi', [NMIController::class, 'ipn'])->name('NMI');
Route::any('btc-pay', [BTCPayController::class, 'ipn'])->name('BTCPay');
Route::post('now-payments-hosted', [NowPaymentsHostedController::class, 'ipn'])->name('NowPaymentsHosted');
Route::post('now-payments-checkout', [NowPaymentsCheckoutController::class, 'ipn'])->name('NowPaymentsCheckout');
Route::post('2checkout', [TwoCheckoutController::class, 'ipn'])->name('TwoCheckout');
Route::any('checkout', [CheckoutController::class, 'ipn'])->name('Checkout');
Route::post('sslcommerz', [SslCommerzController::class, 'ipn'])->name('SslCommerz');
Route::post('aamarpay', [AamarpayController::class, 'ipn'])->name('Aamarpay');
Route::get('binance', [BinanceController::class, 'ipn'])->name('Binance');

Route::get('/payment/success/{deposit_id}', [PaymentController::class,'success'])->name('payment.success');
Route::get('/payment/cancel/{deposit_id}', [PaymentController::class,'cancel'])->name('payment.cancel');
